# Generated by Django 5.1.1 on 2024-12-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=20, unique=True)),
                ('train_name', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('station_from', models.CharField(max_length=100)),
                ('station_to', models.CharField(max_length=100)),
                ('schedule', models.JSONField()),
            ],
        ),
    ]
