# Generated by Django 5.1.1 on 2024-12-29 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project3', '0002_train'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='train',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='train',
            name='station_from',
        ),
        migrations.RemoveField(
            model_name='train',
            name='station_to',
        ),
        migrations.AlterField(
            model_name='train',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_trains', to='project3.station'),
        ),
        migrations.AlterField(
            model_name='train',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_trains', to='project3.station'),
        ),
        migrations.CreateModel(
            name='TrainStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('stop_number', models.IntegerField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project3.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project3.train')),
            ],
            options={
                'unique_together': {('train', 'station')},
            },
        ),
        migrations.AddField(
            model_name='train',
            name='stations',
            field=models.ManyToManyField(through='project3.TrainStation', to='project3.station'),
        ),
    ]
